### Find All COntent
GET http://localhost:8080/api/content

### Get content by ID
GET http://localhost:8080/api/content/1

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": null,
  "title": "Segundo Post",
  "description": "Descripcion fea",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-02-17T21:21:54.6315271",
  "dateUpdated": null,
  "url": ""
}

### Update existing Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MI PRIMER POST",
  "description": "DESCRIPCION FEA",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-02-17T21:21:54.6315271",
  "dateUpdated": "2024-02-17T21:21:54.6315271",
  "url": "http://localhost:8080/un-blog"
}

### delete by id
DELETE http://localhost:8080/api/content/2
